Repository Daniel-Gallagher92/futbol, pull requests merged in 2023-06, with the labels that each got.

#7 SimpleCov Added
  .gitignore
  Gemfile
  Gemfile.lock
  spec/.gitkeep
  spec/spec_helper.rb
Labels: enhancement

#9 Readme
  README.md
Labels: documentation

#12 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#35 Csv data reader
  data/small_game_teams.csv
  data/small_games.csv
  lib/.keep
  lib/game.rb
  lib/game_team.rb
  lib/stats_manager.rb
  lib/team.rb
  spec/game_spec.rb
  spec/game_team_spec.rb
  spec/spec_helper.rb
  spec/stats_manager_spec.rb
  spec/team_spec.rb
Labels: enhancement, Iteration 2

#39 38 merge stats_manager into stat_tracker
  lib/stat_tracker.rb
  spec/spec_helper.rb
  spec/stat_tracker_spec.rb
  spec/stats_manager_spec.rb
Labels: enhancement, Iteration 2

#41 feat: count of teams method and test
  lib/stat_tracker.rb
  spec/stat_tracker_spec.rb
Labels: enhancement, Iteration 2

#44 Feat: Module to find percentages
  lib/percentable.rb
  spec/percentable_spec.rb
Labels: enhancement

#45 23+24: Add best_offense and worse_offense methods
  lib/stat_tracker.rb
  spec/stat_tracker_spec.rb
Labels: enhancement, Iteration 2

#49 #14 + #15 Add highest_total_score and lowest_total_score
  lib/stat_tracker.rb
  spec/stat_tracker_spec.rb
Labels: enhancement

#46 16 + 17 + 18: percentage_home_wins, percentage_visitor_wins and percentage_of_ties
  lib/stat_tracker.rb
  spec/stat_tracker_spec.rb
Labels: enhancement, Iteration 2

#50 Fix: indention and percent_ties naming
  lib/stat_tracker.rb
  spec/stat_tracker_spec.rb
Labels: bug

#53 52 fix rounding bugs
  lib/percentable.rb
  lib/stat_tracker.rb
  spec/percentable_spec.rb
Labels: bug, enhancement

#51 19 method count of games by season
  lib/stat_tracker.rb
  spec/stat_tracker_spec.rb
Labels: enhancement, Game Statistics

#54 31/32 method most/least accurate team
  lib/stat_tracker.rb
  spec/stat_tracker_spec.rb
Labels: enhancement, Iteration 2

#56 #29 + #30 winningest_coach, worst_coach and some unsolicited strong opinions
  lib/stat_tracker.rb
  spec/stat_tracker_spec.rb
Labels: enhancement

#58 Highest lowest home visitors
  lib/stat_tracker.rb
  spec/stat_tracker_spec.rb
Labels: enhancement, Iteration 2

#60 Feat: Create runner to show work
  runner.rb
Labels: enhancement

#62 docs: add retro QAs to README
  README.md
Labels: documentation

#65 63 refactor incorporate team name from id method
  lib/stat_tracker.rb
Labels: enhancement, refactor
